baseURL = "http://example.org/"
languageCode = "fr-FR"
title = "Test for hugo-quickstart"
theme = "casper"
paginate = 5
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "Tous droits réservés - 2018"

[params]

description = "Bien démarrer avec Hugo"

metadescription = "Utilisé dans la balise meta 'description' pour l’accueil et les pages d’index, faute de quoi c'est l’entrée 'description' du front matter de la page qui sera utilisé."

#cover = "/static/img/darius-soodmand-116253.jpg"
#cover = "/src/img/darius-soodmand-116253.jpg"
cover = "images/darius-soodmand-116253.jpg"

author = "Benjamin SICARD"

authorlocation = "Paris, France"

authorwebsite = ""

authorbio= ""

logo = ""

hjsStyle = "default"

paginatedsections = ["posts"]